# Site settings
title: Java Design Patterns
description: Java Design Patterns
# > # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.

baseurl: "/java-design-patterns" # the subpath of your site, e.g. /blog/
url: "http://iluwatar.github.io" # the base hostname & protocol for your site
designer_github_username: Gaohaoyang
permalink: /:year/:month/:day/:title/

# Build settings
markdown: kramdown

# highlight
# highlighter: pygments
# highlighter: rouge
# highlighter: false

kramdown:
  input: GFM

category-list:
  - pattern_cat
  - creational
  - structural
  - concurrency
  - behavioral
  - architectural
  - integration
  - presentation_tier
  - business_tier

tag-list:
  - pattern_tag
