# Site settings
title: Java Design Patterns
description: Java Design Patterns
# > # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.

baseurl: "/java-design-patterns" # the subpath of your site, e.g. /blog/
url: "https://iluwatar.github.io" # the base hostname & protocol for your site
repo_url: "https://github.com/iluwatar/java-design-patterns"
designer_github_username: Gaohaoyang
permalink: /:year/:month/:day/:title/

# Build settings
markdown: kramdown

gems:
  - jekyll-sitemap

kramdown:
  input: GFM
  smart_quotes: ["apos", "apos", "quot", "quot"]
  hard_wrap: false
  default_lang: java

category-list:
  - Other
  - Creational
  - Structural
  - Concurrency
  - Behavioral
  - Architectural
  - Integration
  - Presentation Tier
  - Business Tier

tag-list:
  - Java
